version: '3'

services:
  app:
    build: . # Dockerfile shu joriy katalogda joylashgan
    depends_on: # app ni run qilishdan oldin db ni run qil
      - db
    environment: # Muhit o'zgaruvchilari
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000 # Django ilovasi serverini ishga tushirish

  db:
    image: postgres:9.6 # PostgreSQL tasviri
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes: # Ma'lumotlar saqlanadigan katalog
      - ./data/db:/var/lib/postgresql/data