# Generated by Django 4.2.11 on 2024-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_remove_album_source_album_artist_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listened',
            field=models.BigIntegerField(default=0),
        ),
    ]
